DROP PROC IF EXISTS pr_datosFotos
GO

CREATE PROC pr_datosFotos
@NOMBREEXPO VARCHAR(60),
@STR VARCHAR(60) OUT
AS
BEGIN
	SELECT @STR = CASE WHEN EXISTS (SELECT 1 FROM ARTISTICA A WHERE A.CODIGO = F.CODIGO)
		THEN 'ARTISTICA'
		ELSE 'DOCUMENTAL'
		END + ' ' + F.NOME + ' -' + (SELECT NOME FROM FOTOGRAFO FO WHERE FO.CODIGO = F.COD_FOTOGRAFO) + '-'
	FROM FOTOGRAFIA F
	
	WHERE COD_EXPOSICION = (SELECT CODIGO FROM EXPOSICION WHERE NOME = @NOMBREEXPO)
END
GO
