DROP PROC IF EXISTS pr_LocalidadProvincia
GO

CREATE PROC pr_LocalidadProvincia
@NOMBRE VARCHAR(60),
@LOCALPROV VARCHAR(60) OUT
AS
BEGIN

	SELECT @LOCALPROV = L.NOME + '(' + P.NOME + ')' FROM EXPOSICION E
	JOIN LOCALIDADE L ON E.COD_LOCALIDADE = L.CODIGO
	JOIN PROVINCIA P ON L.COD_PROVINCIA = P.CODIGO
	WHERE E.NOME = @NOMBRE
END
GO